### PR TITLE
Twitter Login fixes #16

### LINKED ISSUE #16: Twitter Login

### PR DESCRIPTION
**Pull request by bkawk**
The button on the top bar, could read, "login with twitter" or use the twitter icon + the word "login" this way the user wold expect that hey going to be redirected to twitter. When they press the button we would then need to show a spinner while we ask the api for for a redirect url, then once we have the url we can redirect the user over to twitter.

or we could have a login button, when pressed asks the api to generates the redirect URL, and at the same time the user is informed via the modal that they are going to be redirect to twitter, once the redirect URL is returned we redirect them over.

The twitter url is to be generated for each visitor wishing to login, the token/url is short lived so we need to make it on demand. The request to our server results results in another request to twitter and back, this delay IMO needs a spinner or redirect message.

Using a modal allows the user, in the future to select from different oauth providers before being redirected.

### CODE REVIEW

**Comment by sbeleidy** [comment]
Can we connect this to the API and see how long it will actually take? I have a feeling we won't need a spinner and modal and all that.

Do we plan on allowing other oauth providers? if so, this component would function the same inside a <login-modal> that could have <twitter-login>, <fb-login>, <google-login> and <email-login>.
The <twitter-login> element should just focus on logging in with twitter and I think we could get away with no spinner for this.

**Comment by bkawk** [comment]
Lets give it a go and see how it feels, ill add in the api connection and do the redirect

**Comment by bkawk** [comment]
I have added the option to change the button text. I have added the twitter icon as an SVG, the color can be changed from white to blue. There is still an event listener that i cant figure out ho to move to the listeners section, please can you take a look at it.

**Comment by sbeleidy** [comment]
We still need to do something about the socket.io ip address in here. It should be a global variable that's passed into the element. Right? Do you want to figure this out now or when we add more elements that interact with sockets?

**Comment by bkawk** [comment]
Lets add this later.
I think we will need to create a tag called convoo-app which will hold the globals and then contain everything within it?

**Pull request merged**
