### PR TITLE
25 image resizer

### PR DESCRIPTION
**Pull request by bkawk**
#25

Image gets resized client side
image can be dragged and dropped or selected
image keeps aspect ration 
image gets centered before cropped
size can be set on the tag
background light or dark can bet set on the tag
image blurs on mouseover
user can select just one image

### CODE REVIEW

**Comment by sbeleidy** [comment]
Can we make the message a property/attribute that's editable when we add each element? It can have a default of "Drop a cover image"?

What do you think about making the remove image on hover only take up a small part of the resizer and not the whole thing? Maybe show in the top right/left?

screen shot 2016-03-29 at 9 41 27 am
Using the light background doesn't update the values for the hover message to remove the image.

How would this work as part of a form? Would it need to reflect the image url to an attribute that can then be used in the form? It looks like you already have a form inside of this but it's not submitting anywhere. When the user drops an image, does it start uploading? Would "remove image" actually delete it from wherever it was uploaded or just remove it from the page? These things would then need to update whatever form the image-resizer is in (I'm guessing with an attribute that can be used when submitting the parent form?).

**Comment by bkawk** [comment]
yes the delete can be made smaller. the text can be made editable. The base 64 for the image is available in the image tag and this will be submited with the rest of the form that this will become part of. The light version not deleting the image I can look into

**Comment by bkawk** [comment]
These changes have been made

**Comment by sbeleidy** [comment]
Just tested dropping an image in and it works, but could you change the text when you're dropping a file that shows that it's droppable? Where we say upload image, it could say "Drop image here" or something like that. What do you think?

**Comment by bkawk** [comment]
The text is now changeable from the custom html tag, do you want different text when you are dragging over?

**Comment by sbeleidy** [comment]
Yeah, when you're dragging over with a file. Should all 3 texts be customizable via attributes? Default text, Dragging file text, Delete image text.

There should be different text while dragging the file in and when the file is actually inside the box there should be some color change or animation so that the user know they can drop it.

**Pull request merged**
