### PR TITLE
SVG Tag Element

### PR DESCRIPTION
**Pull request by bkawk**
#26

SVG tag element
tag resizes to the length of the text
only one line can be entered
delete icon shown on mouseover
tag name can be set on the custom html tag
light and dark backgrounds can be set on the custom html tag
text in the tag can be edited
ready to be included in a new element called tag-list

### CODE REVIEW

**Comment by sbeleidy** [comment]
Let's rename this to convoo-tag so we can use tag-list to list a bunch of convoo-tags. 

Editing the tag's text doesn't resize it. 

Pressing space should exit the tag. Technically the user would be typing in another element and when they press space it creates a convoo-tag? We may want to discuss how this works.

What do you think of making tags all lowercase instead of all uppercase?

**Comment by bkawk** [comment]
I have made the element all lowercase and on blur and focus it now removes and adds the _

**Comment by sbeleidy** [comment]
We should make the tag's value reflectToAttribute: true so we can use it when we're working with these. I'm still not sure how exactly we're gonna be using these. We might just have to modify this element when building the new-room page. 
There may also be 2 versions of this, one that's editable and another that isn't. So when you're on the room, you can view all the tags using this element and when you're creating tags, you could also use the same element.

We can also handle the reflectToAttribute true when we're working with it next. Let me know which approach you want to take. I'm fine merging this in so we can start adding it in other places and modifying it as needed. We just need to be aware of all changes being made to it.

**Comment by bkawk** [comment]
I can make a flag for editable or not and reflect the value into the tag

**Pull request merged**
